# Generated by Django 4.1.1 on 2022-09-30 13:58

from django.db import migrations
from ..group_creation import create_group_user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group_user),
    ]
