version: "3.7"

services:

  db:
    container_name: db_shop
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    container_name: nginx_shop
    build: ./nginx
    depends_on:
      - drf_proj
    volumes:
      - ./static:/static/
      - ./media:/media/
    ports:
      - "1337:80"

  drf_proj:
    container_name: drf_shop
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      - db

  redis:
    container_name: redis_shop
    image: redis
    ports:
      - "6379:6379"

  celery:
    container_name: celery_shop
    build: .
    env_file:
      - .env
    links:
      - redis
    command: celery -A DRF_Project worker -l INFO
    depends_on:
      - db
      - drf_proj
      - redis

volumes:
  pg_data: {}
