# Generated by Django 4.1.1 on 2022-10-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='category_images/'),
        ),
    ]
