# Generated by Django 4.1.1 on 2022-09-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='Order price')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Quantity')),
                ('city', models.CharField(default=None, max_length=80, null=True, verbose_name='City')),
                ('address', models.CharField(default=None, max_length=150, null=True, verbose_name='Address')),
                ('status', models.CharField(choices=[('CART', 'Cart'), ('CREATED', 'Created'), ('PAID', 'Paid'), ('IS_DELIVERING', 'Is Delivering'), ('DELIVERED', 'Delivered')], default='CART', max_length=13)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('product_name', models.CharField(max_length=50, null=True, verbose_name='Product name')),
                ('unit_price', models.IntegerField(null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Item in order',
                'verbose_name_plural': 'Items in order',
            },
        ),
    ]
